Message.create(text: 'Hello! It\'s great to connect with you')
Message.create(text: 'Selam New')
Message.create(text: 'Welcome!')
Message.create(text: 'Selam Aleykum')
Message.create(text: 'Bienvenue')